[package]
name = "rivers"
version = "0.1.0"
authors = ["Tyler Horton <tylerhortonc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.126"
erased-serde = "0.3"
anyhow = "1.0"